spring.application.name=unishop
spring.datasource.url=jdbc:mysql://5.tcp.ngrok.io:29865/base8
spring.datasource.username=estudiantedes3
spring.datasource.password=desarrollo2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Jakarta Mail (SMTP Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=unishop314@gmail.com
spring.mail.password=xpwuhhailjyvfdae
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# MercadoLibre OAuth (el client-id se inyecta en ProductoController)
mercadolibre.client-id=6904866111603024
mercadolibre.client-secret=qVyireyFbJqUSyNPRha0oTQg1SCz6uij
mercadolibre.redirect-uri=https://api.unishop.com/oauth/mercadolibre/callback
